### ISSUE TITLE
Push new version to npm? (fix for falsy return values)

### ISSUE THREAD

**Issue by kowalski** [saulshanabrook/webview-crypto#9]
Hi there,

Great work with this package, I really appreciate your work.

I was struck today with the issue, which I can is has been fixed in March 2020 (https://github.com/webview-crypto/webview-crypto/commit/277143f532373c126e86892c514960d8d9bd85da). 
However I can see that the version uploaded to npm doesn't include this fix. 
Is there a plan to push new version to npm?

**Comment by LinusU** [comment]
Released 0.1.11 🚀
